### ISSUE TITLE
Clarify what is part of UberJAR

### ISSUE THREAD

**Issue by kwin** [justinedelson/aem-uberjar-demo#1]
in your pom.xml you still reference 

```
<dependency>
            <groupId>org.apache.sling</groupId>
            <artifactId>org.apache.sling.api</artifactId>
            <version>2.2.0</version>
</dependency>
```

although the Sling API is part of that UberJAR. Could you clarify what exactly is part of the UberJAR? E.g. I have seen that the Servlet API and JCR API is not exported, although it is clearly part of AEM (i.e. is exposed from running bundles in AEM).

**Comment by justinedelson** [comment]
Thanks for catching that. It was in error. http://adobe.ly/1MCJ7ny has the list of open source projects included in the UberJar.

**Comment by kwin** [comment]
Great, thanks for the information and the update.
