### ISSUE TITLE
Upgrade servlet-api version to 3.1

### ISSUE THREAD

**Issue by jonekdahl** [justinedelson/aem-uberjar-demo#2]
Hi,

I was surprised to see servlet-api:2.5 in the example pom since it is my understanding that AEM 6.1 exposes version 3.1. When I search for "javax.servlet" in the depfinder of an AEM 6.1 instance, it reports that versions 2.6.0, 3.0.0 and 3.1.0 are provided by org.apache.felix.http.servlet-api.

It should be safe to upgrade to Servlet 3.1, right?

**Comment by justinedelson** [comment]
This is correct, although in a WAR deployment, it is dependent upon the application server.
